// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resumedto.proto

package resumebasegradle.net.illay.resumebase.dto;

public interface ResumeDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:illay.ResumeDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required string surname = 3;</code>
   * @return Whether the surname field is set.
   */
  boolean hasSurname();
  /**
   * <code>required string surname = 3;</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <code>required string surname = 3;</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>required string email = 4;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>required string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>required string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>required string phoneNumber = 5;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>required string phoneNumber = 5;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>required string phoneNumber = 5;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>required string skills = 6;</code>
   * @return Whether the skills field is set.
   */
  boolean hasSkills();
  /**
   * <code>required string skills = 6;</code>
   * @return The skills.
   */
  java.lang.String getSkills();
  /**
   * <code>required string skills = 6;</code>
   * @return The bytes for skills.
   */
  com.google.protobuf.ByteString
      getSkillsBytes();

  /**
   * <code>required string education = 7;</code>
   * @return Whether the education field is set.
   */
  boolean hasEducation();
  /**
   * <code>required string education = 7;</code>
   * @return The education.
   */
  java.lang.String getEducation();
  /**
   * <code>required string education = 7;</code>
   * @return The bytes for education.
   */
  com.google.protobuf.ByteString
      getEducationBytes();

  /**
   * <code>required string expirience = 8;</code>
   * @return Whether the expirience field is set.
   */
  boolean hasExpirience();
  /**
   * <code>required string expirience = 8;</code>
   * @return The expirience.
   */
  java.lang.String getExpirience();
  /**
   * <code>required string expirience = 8;</code>
   * @return The bytes for expirience.
   */
  com.google.protobuf.ByteString
      getExpirienceBytes();
}
