// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resumedto.proto

package resumebasegradle.net.illay.resumebase.dto;

public final class ResumeDtoGenerated {
  private ResumeDtoGenerated() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_illay_ResumeDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_illay_ResumeDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017resumedto.proto\022\005illay\"\221\001\n\tResumeDto\022\n" +
      "\n\002id\030\001 \002(\004\022\014\n\004name\030\002 \002(\t\022\017\n\007surname\030\003 \002(" +
      "\t\022\r\n\005email\030\004 \002(\t\022\023\n\013phoneNumber\030\005 \002(\t\022\016\n" +
      "\006skills\030\006 \002(\t\022\021\n\teducation\030\007 \002(\t\022\022\n\nexpi" +
      "rience\030\010 \002(\tBA\n)resumebasegradle.net.ill" +
      "ay.resumebase.dtoB\022ResumeDtoGeneratedP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_illay_ResumeDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_illay_ResumeDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_illay_ResumeDto_descriptor,
        new java.lang.String[] { "Id", "Name", "Surname", "Email", "PhoneNumber", "Skills", "Education", "Expirience", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
